### PR TITLE
Update snapshots, changelog

### PR DESCRIPTION
**Pull request by p-foucht**
**Issue #:** 

**Description of changes:**
- Update failing snapshots
- Update changelog to include hotfix
- Add setSinkId check to demo TestSound

**Testing**
1. Have you successfully run `npm run build:release` locally?

2. How did you test these changes?

3. If you made changes to the component library, have you provided corresponding documentation changes?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by anuranduttaroy — APPROVED** [review]

**Comment by bradmanAWS** [comment]
Did you confirm the new snapshots do actually look correct?

**Comment by p-foucht** [comment]
@bradmanAWS  I think that's a better question for you or the clients team that made the updates. Would you mind taking a look and confirming before we merge this in?

**Comment by bradmanAWS** [comment]
> @bradmanAWS I think that's a better question for you or the clients team that made the updates. Would you mind taking a look and confirming before we merge this in?

Yes, I'll take a look at it now. I'm fine with this not blocking the release.

**Comment by p-foucht** [comment]
> > @bradmanAWS I think that's a better question for you or the clients team that made the updates. Would you mind taking a look and confirming before we merge this in?
> 
> Yes, I'll take a look at it now. I'm fine with this not blocking the release.

Cool thanks -- we'll need snapshot tests passing since it's basically a preflight step in the release MCM

**Review by bradmanAWS — APPROVED** [review]

**Pull request merged**
