### PR TITLE
Add icons for Like, Dislike and Feedback

### PR DESCRIPTION
**Pull request by abey-george**
**Issue #:** 
We need icons for Like, Dislike and Feedback to build out a Ratings component, as well as a Feedback modal.

**Description of changes:**
Adding icons for Like, Dislike and Feedback. 

**Testing**
1. Have you successfully run `npm run build:release` locally?
Yes.

2. How did you test these changes?
Testing by creating new stories for these icons in Storybook.

3. If you made changes to the component library, have you provided corresponding documentation changes?
Yes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by nicklera1** [comment]
Please update CHANGELOG under Add section.

**Comment by bradmanAWS** [comment]
We should also include snapshot tests for any visual changes. Writing snapshot tests is easy. Once you open the story for the component, there is an icon in the upper right to show the component fullscreen without the storybook UI. You can use those query parameters for the docker url. See any test in `tst/snapshots/` for reference. Make sure storybook is running locally when you run `npm run test:snapshots`.

**Comment by abey-george** [comment]
@nicklera1 Updated the CHANGELOG

**Comment by abey-george** [comment]
I updated the CHANGELOG and I saw @bradmanAWS edit on not blocking on snapshots. Let me know if there is anything more I need to do here to move forward. Thanks!

**Review by bradmanAWS — APPROVED** [review]

**Pull request merged**
