### PR TITLE
Added tabIndex property support to BaseProps

### PR DESCRIPTION
**Pull request by alpjor**
**Issue #:** 

**Description of changes:**

Added tabIndex property support to BaseProps
**Testing**
1. Have you successfully run `npm run build:release` locally? yes

2. How did you test these changes? typescript in UCBuzzExpress Library

3. If you made changes to the component library, have you provided corresponding documentation changes? no

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by davejlane — APPROVED** [review]

**Review by davejlane — COMMENTED** [review]
Don't forget to update the CHANGELOG

**Review by p-foucht — DISMISSED** [review]

**Comment by alpjor** [comment]
Are we waiting to merge this? I'm kinda stuck w/o it

**Comment by p-foucht** [comment]
Can you fix the conflict and I'll approve and merge it in?

**Review by bradmanAWS — APPROVED** [review]

**Comment by p-foucht** [comment]
@alpjor Still some conflicts 😅

**Comment by alpjor** [comment]
Screen Shot 2020-10-15 at 3 56 24 PM
 What am I missing?

**Comment by bradmanAWS** [comment]
> Screen Shot 2020-10-15 at 3 56 24 PM
> 
> What am I missing?

Weird, I see "This branch cannot be rebased due to conflicts" even after refreshing on my end.

**Comment by p-foucht** [comment]
Screen Shot 2020-10-15 at 3 58 26 PM

Hm, that's strange, I'm not getting the same status as you. @bradmanAWS Are you able to merge this in?

**Comment by bradmanAWS** [comment]
> Screen Shot 2020-10-15 at 3 58 26 PM
> 
> Hm, that's strange, I'm not getting the same status as you. @bradmanAWS Are you able to merge this in?

I can't. Did you try to `git pull origin master --rebase` and push again?

**Comment by alpjor** [comment]
sorry... How about now?

**Review by p-foucht — APPROVED** [review]

**Comment by p-foucht** [comment]
Still conflicts. I'll just submit a quick PR for the tabIndex

**Comment by p-foucht** [comment]
[Closing for 242](https://github.com/aws/amazon-chime-sdk-component-library-react/pull/242)

**Comment by alpjor** [comment]
Thanks for your help!

**Pull request closed without merging**
