### PR TITLE
Fix wrong import statement in meeting demo

### PR DESCRIPTION
**Pull request by xuesichao**
**Issue :** 
Several import statements import enum `DeviceLabels` from a wrong place.

**Description of changes:**
Fix the import statements.

**Testing**
1. Have you successfully run `npm run build:release` locally?
  Yes

2. How did you test these changes?
  Run meeting demo and it renders correctly and functions well.

3. If you made changes to the component library, have you provided corresponding documentation changes?
  N/A

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jing-chen1 — APPROVED** [review]

**Comment by subhendukundu** [comment]
Will this be published to be used `DeviceLabels`?
ATM in 2.5.0,  I can not do something like below?
```
await meetingManager.join({
        meetingInfo: JoinInfo.Meeting,
        attendeeInfo: JoinInfo.Attendee,
        deviceLabels: DeviceLabels.None,
```

**Comment by xuesichao** [comment]
> When will this be published to be used `DeviceLabels`?
> ATM in 2.5.0, I can not do something like below? I want audio and video to be off for some user by default.
> 
> ```
> await meetingManager.join({
>         meetingInfo: JoinInfo.Meeting,
>         attendeeInfo: JoinInfo.Attendee,
>         deviceLabels: DeviceLabels.None,
> ```

@subhendukundu Hi! 
In 2.5.0, we don't support this it. We add this new feature in 2.6.0, you could check this PR [#499 ](https://github.com/aws/amazon-chime-sdk-component-library-react/pull/499) for more information. We add a simple instruction in CHANGELOG. The 2.6.0 release is under testing, if things go well, it should be published to npm today or next Monday.

This feature doesn't support Firefox and Safari. But we are working on it right now.

You could run meeting demo in master branch to try the new view-only experience. Check below notes before you trying meeting demo.

#### Note 1
Due to a known [issue](https://github.com/aws/amazon-chime-sdk-js/issues/474), in Desktop: Firefox and Safari:
* User joins a meeting selecting "Join w/o Audio and Video". 
* User is expected not to be displayed in the Roster list, and not to be connected to the server. 

_This behavior disappears after following steps:_
* User clicks "Device" button in `MeetingControl` and grant the permission to browser
* `MeetingControl` transform to the normal one
* Select an valid audio input device from `MeetingControl`
* Wait for around 30s, user appears in Roaster and connected to the server
* Everything should function well now.

#### Note 2
In Roster, the microphone icon for view-only mode user is in enable status after user joins the meeting, but there is no activity. 
This is a known bug to us, you can ignore it at this time.

**Comment by subhendukundu** [comment]
Thank you so much. Super helpful.
I was also thinking, why we don't do alpha or beta releases? We could give this a try while it's building and keep continuous testing in the loop too. Just a thought.

**Comment by xuesichao** [comment]
@subhendukundu You're welcome! For release process, our current release cycle mostly contain minor version with bug fixes. People usually do alpha and beta release for major version and not minor version. 
But we do have improvements to do to our release process. We would love to take your thought into consideration. Thanks!

**Pull request merged**
