### PR TITLE
nameplate for localvideo in videotile grid

### PR DESCRIPTION
**Pull request by vinuv00702**
**Issue #:** 
### 
**Description of changes:**
**_nameplate for localvideo in videotile grid_**

**Testing**
1. Have you successfully run `npm run build:release` locally?

2. How did you test these changes?

3. If you made changes to the component library, have you provided corresponding documentation changes?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by michhyun1** [comment]
@vinuv00702 seems like you'll need to rebase your changes

**Review by devalevenkatesh — CHANGES_REQUESTED** [review]
Hello, thanks for your PR and making the React library better and adding the Chat feature to the React SDK demo. I see that there are two separate features in this PR and the `VideoTileGrid` update is also included in [this other](https://github.com/aws/amazon-chime-sdk-component-library-react/pull/581) PR, could you please remove it then from this PR?

Also, we would appreciate if you add a detailed description on what you are changing and how? We have a PR template which is currently missing the required information.

We will discuss within the team on the Chat feature addition and provide an update.

**Review by devalevenkatesh — CHANGES_REQUESTED** [review]
Could you please check few points below?
1. The demo/meeting is moved to a new location now. Its under [`aws-samples/amazon-chime-sdk`](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/meeting) repository. You have to open this PR there now.
2. We request you to extend the existing README with the content as is saying that the demo chat functionality is implemented using the non-persistent messaging using data messages but for persistent messaging implementation please check the [chat demo](https://github.com/aws-samples/amazon-chime-sdk/tree/main/apps/chat).

**Comment by devalevenkatesh** [comment]
Closing this PR in favor of this PR:
https://github.com/aws-samples/amazon-chime-sdk/pull/33

**Comment by devalevenkatesh** [comment]
Sorry see chat added in this PR and is different from above linked PR but request you to open this PR in the aws-samples `amazon-chime-sdk-js` repo.
https://github.com/aws-samples/amazon-chime-sdk

**Pull request closed without merging**
